### ISSUE TITLE
抄也要抄得有尊严啊！

### ISSUE THREAD

**Issue by kiinlam** [zhengguorong/xbossdebug-wechat#1]
fundebug的代码，你拿来改下变量名，函数顺序都没变，就当成自己的了？
连截图都是在他们网站上截的，你连个来源都不写？
好意思说自己是程序员？

**Comment by kiwenlau** [comment]
感谢 @kiinlam 为Fundebug发声！

**Comment by zhengguorong** [comment]
@kiinlam 感谢你的建议，代码确实是借鉴了fundebug的，我稍后会在README上声明的。
但是该开源无意损害fundebug的利益，文章下面也附上了代码解读的思想。

**Comment by Fundebug** [comment]
@kiinlam 

- 代码不是借鉴，是像素级抄袭Fundebug，只是换了一下函数名，函数和数组元素的顺序都没变。

- 用了Fundebug的网站截图，没有任何说明，这一点更加过分。

- 我们要求在所有博客的第一行附上借鉴Fundebug的声明。

- Fundebug保留使用法律手段的权利。

这里附上你的代码和Fundebug的代码，由大家去评论是非。


[xbossdebug-wechat.zip](https://github.com/zhengguorong/xbossdebug-wechat/files/1957180/xbossdebug-wechat.zip)
[fundebug.0.1.3.min.js.zip](https://github.com/zhengguorong/xbossdebug-wechat/files/1957181/fundebug.0.1.3.min.js.zip)

**Comment by zhengguorong** [comment]
@Fundebug 非常抱歉给您带来不便，如果损害到你的利益，我愿意把项目撤下，并对代码进行重构

**Comment by Fundebug** [comment]
@zhengguorong 附上声明就好啦，以后不要再这样了啊....当然，我们以后会混淆代码...
