### ISSUE TITLE
为什么我将xbossdebug放在App.js 中没有自动收集错误

### ISSUE THREAD

**Issue by dogthirteen** [zhengguorong/xbossdebug-wechat#10]
博主方便加个微信请教一下吗，谢谢

**Comment by zhengguorong** [comment]
你把你的问题报错截图上传这里就好，我会抽时间解答的

**Comment by dogthirteen** [comment]
我现在的是吧xbossdebug放在app.js中 然后再别的页面文件中 引入这个方法  手打 log，debug等，能自动收集错误吗
![image](https://user-images.githubusercontent.com/47291177/71507809-bc86bc80-28c0-11ea-83f1-aced5379f227.png)
![image](https://user-images.githubusercontent.com/47291177/71507825-cb6d6f00-28c0-11ea-99bc-20ef31890314.png)
